version: '3.9'
services:

  nginx:
    container_name: vcs_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"

  php:
    container_name: vcs_php
    image: peerasakp/php7-4
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
    expose:
      - "9000"

  db:
    container_name: vcs_db
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    env_file:
      - ./mariadb/vcs_db.env
  
  phpmyadmin:
    container_name: vcs_php_by_admin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    