-- MySQL Script generated by MySQL Workbench
-- Sat Mar  5 23:37:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";



--
-- Table structure for table `vcs_user`
--
CREATE TABLE `vcs_user` (
  `use_id` int NOT NULL AUTO_INCREMENT COLLATE utf8_unicode_ci COMMENT 'ไอดีของ User', 
  `use_name` VARCHAR(100) NOT NULL COLLATE utf8_unicode_ci COMMENT ' ชื่อของ User ',
  `use_username` VARCHAR(45) NOT NULL COLLATE utf8_unicode_ci COMMENT ' ชื่อผู้ใช้ของ User ',
  `use_password` VARCHAR(45) NOT NULL COLLATE utf8_unicode_ci COMMENT ' รหัสผ่านของ User ',
  `use_status` int NOT NULL COLLATE utf8_unicode_ci COMMENT ' สถานะของ User เช่น 1 = ผู้ใช้ทั่วไป, 2 = แอดมิน',
  `use_point` int DEFAULT NULL COLLATE utf8_unicode_ci COMMENT ' คะเเนนที่สามารถโหวตได้ของ User ',
  PRIMARY KEY (`use_id`)
)ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `vcs_vote`
-- -----------------------------------------------------
CREATE TABLE `vcs_vote` (
  `vot_id` int NOT NULL AUTO_INCREMENT COLLATE utf8_unicode_ci COMMENT 'ไอดีของ Vote',
  `vot_name` VARCHAR(100) NOT NULL COLLATE utf8_unicode_ci COMMENT 'ชื่อของ Vote',
  `vot_status` int NOT NULL COLLATE utf8_unicode_ci COMMENT 'สถานะของ Vote เช่น 1 = ปิด, 2 = เปิด',
  `vot_start_time` DATETIME NOT NULL COLLATE utf8_unicode_ci COMMENT 'เวลาเริ่มโหวตของ Vote',
  `vot_end_time` DATETIME NOT NULL COLLATE utf8_unicode_ci COMMENT 'เวลาปิดโหวตของ Vote',
  PRIMARY KEY (`vot_id`)
)ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `vcs_choice_vote`
-- -----------------------------------------------------
CREATE TABLE `vcs_choice_vote` (
  `cho_id` int NOT NULL AUTO_INCREMENT COLLATE utf8_unicode_ci COMMENT 'ไอดีของ choice vote',
  `cho_name` VARCHAR(100) NOT NULL COLLATE utf8_unicode_ci COMMENT 'ชื่อของ choice vote',
  `cho_score` int NOT NULL COLLATE utf8_unicode_ci COMMENT 'คะเเนนของ choice vote',
  `cho_vot_id` int NOT NULL COLLATE utf8_unicode_ci COMMENT 'ไอดีของ Vote',
  PRIMARY KEY (`cho_id`)
)ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `vcs_history_vote`
-- -----------------------------------------------------
CREATE TABLE `vcs_history_vote` (
  `his_id` int NOT NULL AUTO_INCREMENT COLLATE utf8_unicode_ci COMMENT 'ไอดีของ history vote',
  `his_date_vote` DATETIME NOT NULL COLLATE utf8_unicode_ci COMMENT 'วัน เวลาที่โหวต',
  `his_score` int NOT NULL COLLATE utf8_unicode_ci COMMENT 'คะเเนนของ history vote',
  `his_cho_id` int NOT NULL COLLATE utf8_unicode_ci COMMENT 'ไอดีของ choice vote',
  `his_use_id` int NOT NULL COLLATE utf8_unicode_ci COMMENT 'ไอดีของ user',
  PRIMARY KEY (`his_id`)
)ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


--
-- Constraints for table `vcs_choice_vote`
--
ALTER TABLE `vcs_choice_vote`
  ADD CONSTRAINT `vcs_choice_vote_ibfk_1` FOREIGN KEY (`cho_vot_id`) REFERENCES `vcs_vote` (`vot_id`);

--
-- Constraints for table `vcs_history_vote`
--
ALTER TABLE `vcs_history_vote`
  ADD CONSTRAINT `vcs_history_vote_ibfk_1` FOREIGN KEY (`his_cho_id`) REFERENCES `vcs_choice_vote` (`cho_id`),
  ADD CONSTRAINT `vcs_history_vote_ibfk_2` FOREIGN KEY (`his_use_id`) REFERENCES `vcs_user` (`use_id`);
